title: Open Competency Library
remote_theme: just-the-docs/just-the-docs
description: An open-source repository of software development-related competencies.
show_downloads: false
markdown: kramdown
collections: 
  levels:
    output: true
    sort_by: number
  level_categories:
    output: true
    sort_by: difficulty